config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :songs,          only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <div >
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol>
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_followers.html.erb
<% @user ||= current_user %>
<div >
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" >
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" >
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_song_form.html.erb
<%= form_for(@song) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div >
    <%= f.text_area :song, placeholder: "Add new Song" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.songs.count, "song") %></span>