config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :songs,          only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   
  </head>
  <body>
    <header >
  <div class="container">
    <%= link_to "Brunchtime", root_path, id: "logo" %>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li>
            <a href="#" data-toggle="dropdown">
              Account 
            </a>
            <ul >
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li ></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>